export const GETPRODUCTS_LOADING = 'GETPRODUCTS_LOADING';
export const GETPRODUCTS_FAILURE = 'GETPRODUCTS_FAILURE';
export const GETPRODUCTS_SUCCESS = 'GETPRODUCTS_SUCCESS';

export const SAVEPRODUCTS_LOADING = 'SAVEPRODUCTS_LOADING';
export const SAVEPRODUCTS_FAILURE = 'SAVEPRODUCTS_FAILURE';
export const SAVEPRODUCTS_SUCCESS = 'SAVEPRODUCTS_SUCCESS';